apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/YOUR_GITHUB_REPO/kubernetes-manifests.git"
    targetRevision: HEAD
    path: tomcat-postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
